routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Seniunijos;


Route::get('/', function () {
	$seniunijos = Seniunijos::all();

    return view('welcome', ['seniunijos'=> $seniunijos]);
});
Route::get('/apie', function() {
	return view('about');
})->name('apie');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('seniunijos', 'SeniunijosController');
Route::get('seniunijos/compare/{id1}/{id2}', 'SeniunijosController@compare')->name('compare');
Route::resource('mokymas', 'MokymasController');
Route::resource('stoteles', 'BusController');
Route::resource('street-art', 'StreetArtController');
Route::resource('library', 'LibraryController');
Route::resource('park', 'ParkController');
Route::resource('koloneles', 'GasStationsController');
Route::resource('treniruokliai', 'TreniruokliaiController');
Route::resource('konteineriai', 'KonteineriaiController');
Route::get('seniunijos/{id}/coords', 'SeniunijosController@getCoords');
Route::get('seniunijos/get/all/coords', 'SeniunijosController@getAllCoords');

resources/views/about.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h1 class="text-black-50 text-center mt-3">Kas yra Mano-Rajonas.lt</h1>
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
                industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and
                scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap
                into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the
                release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing
                software like Aldus PageMaker including versions of Lorem Ipsum.
            </div>
        </div>
    </div>
@endsection

resources/views/chart.blade.php
<div  class="col-8 mt-3">
    <div class="row">
        <div class="col-md-12 headingas">
            <h3 class="text-white">Gero gyvenimo koeficientas <br> skirtingoms amžiaus grupėms  {{ $seniunija->pavadinimas }}</h3>
        </div>
        <div class="col-md-4">
            <div class="chart">
                <canvas id="chart-area" width="1140" height="570" style="display: block; height: 285px; width: 570px;"></canvas>
                <div class="chart-number count">
                    {{ sprintf('%f', $seniunija->jaunimas) }}
                    {{--{{ $seniunija->jaunimas }}--}}
                </div>
                <div class="text-white text-desc">
                    Patrauklumas jaunimui
                </div>
            </div>

        </div>
        <div  class="col-md-4">
            <div class="chart">
                <canvas id="chart-area2" width="1140" height="570" style="display: block; height: 285px; width: 570px;"></canvas>
                <div class="chart-number count">
                    {{ $seniunija->seimos }}
                </div>
                <div class="text-white text-desc">
                    Patrauklumas jaunoms šeimoms
                </div>
            </div>

        </div>
        <div class="col-md-4">
            <div class="chart">
                <canvas id="chart-area3" width="1140" height="570" style="display: block; height: 285px; width: 570px;"></canvas>
                <div class="chart-number count">
                    {{ $seniunija->senijorai }}
                </div>
                <div class="text-white text-desc">
                    Patrauklumas senijorams
                </div>
            </div>

        </div>
    </div>
</div>

resources/views/chart2.blade.php
<div  class="col-8 mt-3">
    <div class="row">
        <div class="col-md-12 headingas">
            <h3 class="text-white">Gero gyvenimo koeficientas <br> skirtingoms amžiaus grupėms  {{ $seniunija1->pavadinimas }}</h3>
        </div>
        <div class="col-md-4">
            <div class="chart">
                <canvas id="chart-area4" width="1140" height="570" style="display: block; height: 285px; width: 570px;"></canvas>
                <div class="chart-number count">
                    {{ sprintf('%f', $seniunija1->jaunimas) }}
                    {{--{{ $seniunija->jaunimas }}--}}
                </div>
                <div class="text-white text-desc">
                    Patrauklumas jaunimui
                </div>
            </div>

        </div>
        <div  class="col-md-4">
            <div class="chart">
                <canvas id="chart-area5" width="1140" height="570" style="display: block; height: 285px; width: 570px;"></canvas>
                <div class="chart-number count">
                    {{ $seniunija1->seimos }}
                </div>
                <div class="text-white text-desc">
                    Patrauklumas jaunoms šeimoms
                </div>
            </div>

        </div>
        <div class="col-md-4">
            <div class="chart">
                <canvas id="chart-area6" width="1140" height="570" style="display: block; height: 285px; width: 570px;"></canvas>
                <div class="chart-number count">
                    {{ $seniunija1->senijorai }}
                </div>
                <div class="text-white text-desc">
                    Patrauklumas senijorams
                </div>
            </div>

        </div>
    </div>
</div>

resources/views/first.blade.php
<div class="row">
    <div class="col-md-10 offset-md-1">
        <div class="row">
            <div class="col-md-10 offset-md-1 col-12">
                <h1>Sužinokite ir palyginkite gyvenimo kokybę įvariuose Kauno rajonuose</h1>
            </div>

            @foreach($seniunijos as $seniunija)
                <div class="col-md-3 col-6 seniunija">
                    <div class="seniunija-box">
                        <a href="{{ route('seniunijos.show', [$seniunija->id]) }}" data-sen="{{ $seniunija->id }}">
                            <div class="rajon-bg"
                                 style="background: url(/rajonai/{{ $seniunija->id }}.jpg); background-size: cover; background-position: bottom">

                            </div>
                            <div class="pavadinimas">
                                {{ $seniunija->pavadinimas }}
                            </div>
                        </a>
                    </div>

                </div>
            @endforeach
            <div class="col-md-3 col-6 seniunija">
                <div class="seniunija-box">
                    <a href="{{ route('seniunijos.index') }}" class="all">
                        <div class="rajon-bg"
                             style="background: url(/rajonai/landing.jpg); background-size: cover; background-position: bottom">

                        </div>
                        <div class="pavadinimas">
                            Miesto žemėlapis
                        </div>
                    </a>
                </div>

            </div>
        </div>
    </div>

</div>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/second.blade.php
<div class="row" id="second-row">
    <div class="col-10 offset-1">
        <div class="row">
            <div class="col-10 offset-1">
                <h1 style="opacity: 0;">Sužinokite ir palyginkite gyvenimo kokybę įvariuose Kauno rajonuose</h1>

            </div>

            @foreach($seniunijos as $seniunija)
                <div class="col-md-3 seniunija">
                    <div class="seniunija-box">
                        <a href="{{ route('seniunijos.show', [$seniunija->id]) }}" data-sen="{{ $seniunija->id }}">
                            <div class="rajon-bg"
                                 style="background: url(/rajonai/{{ $seniunija->id }}.jpg); background-size: cover; background-position: bottom">

                            </div>
                            <div class="pavadinimas">
                                {{ $seniunija->pavadinimas }}
                            </div>
                        </a>
                    </div>

                </div>
            @endforeach
            <div class="col-md-3 seniunija">
                <div class="seniunija-box">
                    <a href="{{ route('seniunijos.index') }}">
                        <div class="rajon-bg"
                             style="background: url(/rajonai/landing.jpg); background-size: cover; background-position: bottom">

                        </div>
                        <div class="pavadinimas">
                            Miesto žemėlapis
                        </div>
                    </a>
                </div>

            </div>
        </div>
    </div>
</div>