routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Seniunijos;


Route::get('/', function () {
	$seniunijos = Seniunijos::all();

    return view('welcome', ['seniunijos'=> $seniunijos]);
});
Route::get('/apie', function() {
	return view('about');
})->name('apie');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('seniunijos', 'SeniunijosController');
Route::get('seniunijos/compare/{id1}/{id2}', 'SeniunijosController@compare')->name('compare');
Route::resource('mokymas', 'MokymasController');
Route::resource('stoteles', 'BusController');
Route::resource('street-art', 'StreetArtController');
Route::resource('library', 'LibraryController');
Route::resource('park', 'ParkController');
Route::resource('koloneles', 'GasStationsController');
Route::resource('treniruokliai', 'TreniruokliaiController');
Route::resource('konteineriai', 'KonteineriaiController');
Route::get('seniunijos/{id}/coords', 'SeniunijosController@getCoords');
Route::get('seniunijos/get/all/coords', 'SeniunijosController@getAllCoords');

app/Seniunijos.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Seniunijos extends Model
{
    //

	public function coords() {
		return $this->hasMany('App\SeniunijuKoordinates', 'seniunijos_id', 'id');
	}

	public function svietimas() {
		return $this->hasMany('App\Mokymas', 'seniunijos_id', 'id');
	}

	public function bus_stops() {
		return $this->hasMany('App\BusStops', 'seniunijos_id', 'id');
	}

	public function gas_stations() {
		return $this->hasMany('App\GasStation', 'seniunijos_id', 'id');
	}


	public function treniruokliai() {
		return $this->hasMany('App\Treniruokliai', 'seniunijos_id', 'id');
	}

	public function konteineriai() {
		return $this->hasMany('App\Konteineriai', 'seniunijos_id', 'id');
	}

	public function street_art() {
		return $this->hasMany('App\StreetArt', 'seniunijos_id', 'id');
	}
}

app/Http/Controllers/SeniunijosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Seniunijos;

class SeniunijosController extends Controller {
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {

		$filtrai = [
			[
				"img" => "img/filtras/mokyklos.png",
				"title" => "Mokyklos",
				"color" => "#ffcb29"
			],
			[
				"img" => "img/filtras/degalines.png",
				"title" => "Degalines",
				"color" => "#c5d92d"
			],
			[
				"img" => "img/filtras/stoteles.png",
				"title" => "Stoteles",
				"color" => "#70b2e2"
			],
			[
				"img" => "img/filtras/bibliotekos.png",
				"title" => "Bibliotekos",
				"color" => "#ffcb29"
			],
			[
				"img" => "img/filtras/treniruokliai.png",
				"title" => "Treniruokliai",
				"color" => "#f1592b"
			],
			[
				"img" => "img/filtras/kultura.png",
				"title" => "Kultura",
				"color" => "#ffcb29"
			],
			[
				"img" => "img/filtras/parkai.png",
				"title" => "Parkai",
				"color" => "#41b655"
			],
			[
				"img" => "img/filtras/dviraciai.png",
				"title" => "Dviračiai",
				"color" => "#78909c"
			]

		];
		//
		$seniunijos = Seniunijos::all();

		return view( 'seniunijos.index', [
			'seniunijos' => $seniunijos,
			'filtrai' => $filtrai
		] );

	}

	public function compare( $id1, $id2 ) {

		$seniunija  = Seniunijos::find( 1 );
		$seniunija1 = Seniunijos::find( 2 );

		return view( 'seniunijos.compare', [
			'seniunija' => $seniunija,
			'seniunija1' => $seniunija1
		] );
	}

	public function getAllCoords( Request $request ) {
		$seniunijosKoordinates = Seniunijos::all();

		foreach ( $seniunijosKoordinates as $seniunija ) {
			if ( isset( $seniunija->coords ) ) {
				foreach ( $seniunija->coords as $coord ) {
				}
			}

		}

		return response()->json( $seniunijosKoordinates );
	}

	public function getCoords( Request $request, $id ) {
		$seniunijosKoordinates = Seniunijos::find( $id );

		foreach ( $seniunijosKoordinates->coords as $coord ) {

		}

		return response()->json( $seniunijosKoordinates->coords );
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		//
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function store( Request $request ) {
		//
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function show( $id ) {
		//

		$filtrai = [
			[
				"img" => "img/filtras/mokyklos.png",
				"title" => "Mokyklos",
				"color" => "#ffcb29"
			],
			[
				"img" => "img/filtras/degalines.png",
				"title" => "Degalines",
				"color" => "#c5d92d"
			],
			[
				"img" => "img/filtras/stoteles.png",
				"title" => "Stoteles",
				"color" => "#70b2e2"
			],
			[
				"img" => "img/filtras/bibliotekos.png",
				"title" => "Bibliotekos",
				"color" => "#ffcb29"
			],
			[
				"img" => "img/filtras/treniruokliai.png",
				"title" => "Treniruokliai",
				"color" => "#f1592b"
			],
			[
				"img" => "img/filtras/kultura.png",
				"title" => "Kultura",
				"color" => "#ffcb29"
			],
			[
				"img" => "img/filtras/parkai.png",
				"title" => "Parkai",
				"color" => "#41b655"
			],
			[
				"img" => "img/filtras/dviraciai.png",
				"title" => "Dviračiai",
				"color" => "#78909c"
			]

		];

		$seniunija = Seniunijos::find( $id );

		return view( 'seniunijos.show', [ 'seniunija' => $seniunija, "filtrai" => $filtrai ] );
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit( $id ) {
		//
		$seniunija = Seniunijos::find( $id );

		return view( 'seniunijos.edit', [ 'seniunija' => $seniunija ] );
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function update( Request $request, $id ) {
		//
		$seniunija                     = Seniunijos::find( $id );
		$seniunija->pavadinimas        = $request->pavadinimas;
		$seniunija->gyventoju_skaicius = $request->gyventoju_skaicius;
		$seniunija->plotas             = $request->plotas;
		$seniunija->aprasymas          = $request->aprasymas;

		$seniunija->save();

		return redirect()->route( 'seniunijos.index' );
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function destroy( $id ) {
		//
	}
}

resources/views/seniunijos/compare.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid left-side-single single-rajon">
        <div class="row">
            <div class="col-md-6 right-side-landing py-3 content first-compare">
                <div class="compare-image" style="background: url('/rajonai/{{ $seniunija->id }}.jpg'); background-position: bottom center; background-size: cover;"></div>
                <div class="row rajon-stats">

                    <div class="col-md-8 offset-md-2 offset-2 col-8">
                        <h1>{{ $seniunija->pavadinimas }}</h1>

                        <div class="row stats-row">

                            <div class="col-md-4 col-6">
                                @if($seniunija->gyventoju_skaicius > $seniunija1->gyventoju_skaicius)
                                   <img class="compare-icon" src="/+.png">
                                @else
                                    <img class="compare-icon" src="/-.png">

                                @endif
                                <div class="number count">

                                    {{ $seniunija->gyventoju_skaicius }}
                                </div>
                                <span class="title">Gyventojų skaičius</span>
                            </div>


                            <div class="col-md-4 col-6">
                                @if($seniunija->svietimas > $seniunija1->svietimas)
                                    <img class="compare-icon" src="/+.png">
                                @else
                                    <img class="compare-icon" src="/-.png">

                                @endif
                                <div class="number count">
                                    {{ count($seniunija->svietimas) }}
                                </div>
                                <span class="title">Švietimo įstaigų</span>
                            </div>

                            <div class="col-md-4 col-6">
                                @if($seniunija->bus_stops > $seniunija1->bus_stops)
                                    <img class="compare-icon" src="/+.png">
                                @else
                                    <img class="compare-icon" src="/-.png">
                                @endif
                                <div class="number count">
                                    {{ count($seniunija->bus_stops) }}
                                </div>
                                <span class="title">Autobusų stotelių</span>
                            </div>

                            <div class="col-md-4 col-6">
                                @if($seniunija->gas_stations > $seniunija1->gas_stations)
                                    <img class="compare-icon" src="/+.png">
                                @else
                                    <img class="compare-icon" src="/-.png">
                                @endif
                                <div class="number count">
                                    {{ count($seniunija->gas_stations) }}
                                </div>
                                <span class="title">Degalinių</span>
                            </div>

                            <div class="col-md-4 col-6">
                                @if($seniunija->treniruokliai > $seniunija1->treniruokliai)
                                    <img class="compare-icon" src="/+.png">
                                @else
                                    <img class="compare-icon" src="/-.png">
                                @endif
                                <div class="number count">
                                    {{ count($seniunija->treniruokliai) }}
                                </div>
                                <span class="title">Treniruoklių</span>
                            </div>

                            <div class="col-md-4 col-6">
                                @if($seniunija->konteineriai > $seniunija1->konteineriai)
                                    <img class="compare-icon" src="/+.png">
                                @else
                                    <img class="compare-icon" src="/-.png">
                                @endif
                                <div class="number count">
                                    {{ count($seniunija->konteineriai) }}
                                </div>
                                <span class="title">Konteinerių</span>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

            <div class="col-md-6 right-side-landing py-3 content first-compare">
                <div class="compare-image" style="background: url('/rajonai/{{ $seniunija1->id }}.jpg'); background-position: bottom center; background-size: cover;"></div>
                <div class="row rajon-stats">
                    <div class="col-md-8 offset-md-2 offset-2 col-8">
                        <h1>{{ $seniunija1->pavadinimas }}</h1>

                        <div class="row stats-row">
                            <div class="col-md-4 col-6">
                                @if($seniunija->gyventoju_skaicius < $seniunija1->gyventoju_skaicius)
                                    <img class="compare-icon" src="/+.png">
                                @else
                                    <img class="compare-icon" src="/-.png">
                                @endif
                                <div class="number count">
                                    {{ $seniunija1->gyventoju_skaicius }}
                                </div>
                                <span class="title">Gyventojų skaičius</span>
                            </div>


                            <div class="col-md-4 col-6">
                                @if($seniunija->svietimas < $seniunija1->svietimas)
                                    <img class="compare-icon" src="/+.png">
                                @else
                                    <img class="compare-icon" src="/-.png">
                                @endif
                                <div class="number count">
                                    {{ count($seniunija1->svietimas) }}
                                </div>
                                <span class="title">Švietimo įstaigų</span>
                            </div>

                            <div class="col-md-4 col-6">
                                @if($seniunija->bus_stops < $seniunija1->bus_stops)
                                    <img class="compare-icon" src="/+.png">
                                @else
                                    <img class="compare-icon" src="/-.png">
                                @endif
                                <div class="number count">
                                    {{ count($seniunija1->bus_stops) }}
                                </div>
                                <span class="title">Autobusų stotelių</span>
                            </div>

                            <div class="col-md-4 col-6">
                                @if($seniunija->gas_stations < $seniunija1->gas_stations)
                                    <img class="compare-icon" src="/+.png">
                                @else
                                    <img class="compare-icon" src="/-.png">
                                @endif
                                <div class="number count">
                                    {{ count($seniunija1->gas_stations) }}
                                </div>
                                <span class="title">Degalinių</span>
                            </div>

                            <div class="col-md-4 col-6">
                                @if($seniunija->treniruokliai < $seniunija1->treniruokliai)
                                    <img class="compare-icon" src="/+.png">
                                @else
                                    <img class="compare-icon" src="/-.png">
                                @endif
                                <div class="number count">
                                    {{ count($seniunija1->treniruokliai) }}
                                </div>
                                <span class="title">Treniruoklių</span>
                            </div>

                            <div class="col-md-4 col-6">
                                @if($seniunija->konteineriai < $seniunija1->konteineriai)
                                    <img class="compare-icon" src="/+.png">
                                @else
                                    <img class="compare-icon" src="/-.png">
                                @endif
                                <div class="number count">
                                    {{ count($seniunija1->konteineriai) }}
                                </div>
                                <span class="title">Konteinerių</span>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>

    </div>
    <div class="container-fluid general-stats compare-charts">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    @include('chart')
                </div>
                <div class="col-md-6">
                    @include('chart2')
                </div>
            </div>


        </div>

    </div>
    <div class="container-fluid">
        <div class="row">


        </div>
    </div>

    <div class="map-wrapper">
        <div id="map"></div>
    </div>
    <script>
      var single = true;
      var centras = { lat: {{ $seniunija->svietimas[0]->lat }}, lng: {{ $seniunija->svietimas[0]->lng }} }
    </script>
@endsection

resources/views/seniunijos/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container py-4">


        <h1>Redaguojate: {{ $seniunija->pavadinimas }}</h1>
        <form action="{{ route('seniunijos.update', [$seniunija->id]) }}" method="POST" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{ method_field('put') }}
            <div>
                <input type="text" name="pavadinimas" class="form-control" placeholder="Pavadinimas" value="{{ $seniunija->pavadinimas }}">
            </div>

            <div>
                <input type="file" name="nuotrauka" class="form-control">
            </div>

            <div>
                <input type="text" name="gyventoju_skaicius" class="form-control" placeholder="Gyventoju skaicius">
            </div>

            <div>
                <input type="text" name="plotas" class="form-control" placeholder="plotas">
            </div>

            <textarea class="form-control" name="aprasymas"></textarea>

            <input type="submit" class="btn btn-success">
        </form>

    </div>

@endsection

resources/views/seniunijos/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">

            @foreach($filtrai as $a)
                <div class="filtras" style="background: {{ $a['color'] }}">
                    <div class="mt-3">
                        <img src="{{ asset($a['img']) }}">
                        <div class="text-center">
                            {{ $a['title'] }}
                        </div>
                    </div>

                </div>
            @endforeach
        </div>
    </div>
    <div class="container-fluid">

        <div class="map-wrapper">
            <div id="map"></div>
        </div>
        <table class="table">
            <tr>
                <th>Rajonas</th>
                <th>Svietimo istaigos</th>
                <th>Stoteles</th>
                <th>Koloneles</th>
                <th>Treniruokliu kiekis</th>
                <th>Konteineriu kiekis</th>
            </tr>
            @foreach($seniunijos as $seniunija)
                <tr>
                    <td>
                        {{ $seniunija->pavadinimas }}
                    </td>
                    <td>
                        {{ count($seniunija->svietimas) }}
                    </td>
                    <td>
                        {{ count($seniunija->bus_stops) }}
                    </td>
                    <td>
                        {{ count($seniunija->gas_stations) }}
                    </td>
                    <td>
                        {{ count($seniunija->treniruokliai) }}
                    </td>
                    <td>
                        {{ count($seniunija->konteineriai) }}
                    </td>
                   {{-- <td>
                        <a href="{{ route('seniunijos.edit', [$seniunija->id]) }}">Redaguoti</a>
                    </td>--}}
                </tr>
            @endforeach
        </table>
    </div>


    <script>

    </script>

@endsection

resources/views/seniunijos/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid left-side-single single-rajon" style="background: url(/rajonai/{{ $seniunija->id }}.jpg); background-size: cover; background-position: bottom">
        <div class="row">
            <div class="col-md-12 right-side-landing py-3 content">
                <h1>{{ $seniunija->pavadinimas }}</h1>
                <div class="row rajon-stats">
                    <div class="col-md-8 offset-md-2 offset-2 col-8">
                        <div class="row">
                            <div class="col-md-4 col-6">
                                <div class="number count">
                                    {{ $seniunija->gyventoju_skaicius }}
                                </div>
                                <span class="title">Gyventojų skaičius</span>
                            </div>


                            <div class="col-md-4 col-6">
                                <div class="number count">
                                    {{ count($seniunija->svietimas) }}
                                </div>
                                <span class="title">Švietimo įstaigų</span>
                            </div>

                            <div class="col-md-4 col-6">
                                <div class="number count">
                                    {{ count($seniunija->bus_stops) }}
                                </div>
                                <span class="title">Autobusų stotelių</span>
                            </div>

                            <div class="col-md-4 col-6">
                                <div class="number count">
                                    {{ count($seniunija->gas_stations) }}
                                </div>
                                <span class="title">Degalinių</span>
                            </div>

                            <div class="col-md-4 col-6">
                                <div class="number count">
                                    {{ count($seniunija->treniruokliai) }}
                                </div>
                                <span class="title">Treniruoklių</span>
                            </div>

                            <div class="col-md-4 col-6">
                                <div class="number count">
                                    {{ count($seniunija->konteineriai) }}
                                </div>
                                <span class="title">Konteinerių</span>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>

    </div>
    <div class="container-fluid general-stats">
        <div class="row">
            <div class="col-4 number-hold">
                <div class="big-number count-big">
                    {{ round($seniunija->bendras, 1) }}
                </div>
                <div class="big-desc">

                    Bendras gero gyvenimo koeficientas {{ $seniunija->pavadinimas }}
                </div>
            </div>
           <div  class="col-8 mt-3">
               <div class="row">
                   <div class="col-md-12 headingas">
                       <h3 class="text-white">Gero gyvenimo koeficientas <br> skirtingoms amžiaus grupėms  {{ $seniunija->pavadinimas }}</h3>
                   </div>
                   <div class="col-md-4">
                       <div class="chart">
                           <canvas id="chart-area" width="1140" height="570" style="display: block; height: 285px; width: 570px;"></canvas>
                           <div class="chart-number count">
                               {{ sprintf('%f', $seniunija->jaunimas) }}
                               {{--{{ $seniunija->jaunimas }}--}}
                           </div>
                           <div class="text-white text-desc">
                               Patrauklumas jaunimui
                           </div>
                       </div>

                   </div>
                   <div  class="col-md-4">
                       <div class="chart">
                           <canvas id="chart-area2" width="1140" height="570" style="display: block; height: 285px; width: 570px;"></canvas>
                           <div class="chart-number count">
                               {{ $seniunija->seimos }}
                           </div>
                           <div class="text-white text-desc">
                               Patrauklumas jaunoms šeimoms
                           </div>
                       </div>

                   </div>
                   <div class="col-md-4">
                       <div class="chart">
                           <canvas id="chart-area3" width="1140" height="570" style="display: block; height: 285px; width: 570px;"></canvas>
                           <div class="chart-number count">
                               {{ $seniunija->senijorai }}
                           </div>
                           <div class="text-white text-desc">
                               Patrauklumas senijorams
                           </div>
                       </div>

                   </div>
               </div>
           </div>



        </div>
    </div>
    <div class="container-fluid">
        <div class="row">

            @foreach($filtrai as $a)
                <div class="filtras" style="background: {{ $a['color'] }}">
                    <div class="mt-3">
                        <img src="{{ asset($a['img']) }}">
                        <div class="text-center">
                            {{ $a['title'] }}
                        </div>
                    </div>

                </div>
            @endforeach
        </div>
    </div>
    <div class="map-wrapper">
        <div id="map"></div>
    </div>
    <script>
        var single = true;
        var centras = { lat: {{ $seniunija->svietimas[0]->lat }}, lng: {{ $seniunija->svietimas[0]->lng }} }
    </script>
@endsection